- name: "Creating Ec2 on AWS"
  hosts: localhost
  connection: local
  gather_facts: True
  vars_files:
    - "{{inventory_dir}}/apps/sample1/vars/vault.yml"
    - "{{inventory_dir}}/apps/sample1/vars/common.yml"
    - "{{inventory_dir}}/apps/sample1/vars/dev_vars.yml"
  roles:
     - {role: "{{inventory_dir}}/apps/sample1/roles/create_security_group"}
     - {role: "{{inventory_dir}}/apps/sample1/roles/create_ec2"}


- include: update-ec2.yml

